name: Cabeça de Homem
favicon: null
layout_spectrum: 0.0886703534051776
typography_spectrum: 0.49149831268005073
title: Cabeça de Homem
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-2831534-5
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8125
  lightness: 0.9375
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
